#include "main.h"

const I8U ui_matrix_button_single[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                           UI_DISPLAY_CAROUSEL_1,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                  UI_DISPLAY_SYSTEM_RESTART,
	/*UI_DISPLAY_SYSTEM_OTA,*/                      UI_DISPLAY_SYSTEM_OTA,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                  UI_DISPLAY_SYSTEM_LINKING,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/             UI_DISPLAY_SYSTEM_UNAUTHORIZED,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/               UI_DISPLAY_HOME,		
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                    UI_DISPLAY_CAROUSEL_1,  
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/             UI_DISPLAY_CAROUSEL_1,	
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                     UI_DISPLAY_CAROUSEL_3,		
	/*UI_DISPLAY_SMART_WEATHER,*/                   UI_DISPLAY_CAROUSEL_3,	
	/*UI_DISPLAY_SMART_MESSAGE,*/                   UI_DISPLAY_CAROUSEL_2,
	/*UI_DISPLAY_SMART_APP_NOTIF,*/                 UI_DISPLAY_CAROUSEL_2,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/              UI_DISPLAY_CAROUSEL_2,
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/             UI_DISPLAY_SMART_INCOMING_CALL,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/          UI_DISPLAY_SMART_INCOMING_MESSAGE,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/      UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,*/        UI_DISPLAY_CAROUSEL_3,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                UI_DISPLAY_SMART_IDLE_ALERT,
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/          UI_DISPLAY_SMART_HEART_RATE_ALERT,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/            UI_DISPLAY_SMART_STEP_10K_ALERT,	
	/*UI_DISPLAY_SMART_SOS_ALERT,*/                 UI_DISPLAY_SMART_SOS_ALERT,	
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/                 UI_DISPLAY_CAROUSEL_1,	
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/                     UI_DISPLAY_CAROUSEL_3,
	// 6: Stopwatch
	/*UI_DISPLAY_STOPWATCH_START,*/                 UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_STOPWATCH_STOP,*/                  UI_DISPLAY_STOPWATCH_STOP,
	// 7: Workout mode
	/*UI_DISPLAY_WORKOUT_TREADMILL,*/               UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                 UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                  UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/              UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_ROW,*/                     UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_AEROBIC,*/                 UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_PILOXING,*/                UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                  UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_RT_READY,*/                UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_RT_TIME,*/                 UI_DISPLAY_WORKOUT_RT_TIME,
	/*UI_DISPLAY_WORKOUT_RT_HEART_RATE,*/           UI_DISPLAY_WORKOUT_RT_HEART_RATE,
	/*UI_DISPLAY_WORKOUT_RT_CALORIES,*/             UI_DISPLAY_WORKOUT_RT_CALORIES,
	/*UI_DISPLAY_WORKOUT_RT_END,*/                  UI_DISPLAY_WORKOUT_RT_END,
	// 8: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/           UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/               UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/               UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/             UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/            UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/         UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/           UI_DISPLAY_CAROUSEL_1,
	// 9: training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/             UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_TRAINING_STAT_START_OR_ANALYSIS,*/ UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_TRAINING_STAT_READY,*/             UI_DISPLAY_TRAINING_STAT_READY,
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/              UI_DISPLAY_TRAINING_STAT_TIME,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/          UI_DISPLAY_TRAINING_STAT_DISTANCE,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/              UI_DISPLAY_TRAINING_STAT_PACE,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/        UI_DISPLAY_TRAINING_STAT_HEART_RATE,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/          UI_DISPLAY_TRAINING_STAT_RUN_STOP,
	// 10: CYCLING_OUTDOOR Statistics
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,*/      UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,*/       UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,		
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,*/   UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,*/ UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,*/       UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,	
	// 10: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/                      UI_DISPLAY_HOME,
	/*UI_DISPLAY_CAROUSEL_2,*/                      UI_DISPLAY_HOME,
	/*UI_DISPLAY_CAROUSEL_3,*/                      UI_DISPLAY_HOME,
	// 11: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                         UI_DISPLAY_PREVIOUS,
};

const I8U ui_matrix_finger_middle[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                           UI_DISPLAY_HOME,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                  UI_DISPLAY_SYSTEM_RESTART,
	/*UI_DISPLAY_SYSTEM_OTA,*/                      UI_DISPLAY_SYSTEM_OTA,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                  UI_DISPLAY_SYSTEM_LINKING,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/             UI_DISPLAY_SYSTEM_UNAUTHORIZED,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/               UI_DISPLAY_SYSTEM_BATT_POWER,		
	// 2: a set of the typical use cases 
	/*UI_DISPLAY_TRACKER_STEP,*/                    UI_DISPLAY_TRACKER_STEP,  
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/             UI_DISPLAY_TRACKER_ACTIVE_TIME,		
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                     UI_DISPLAY_SMART_PM2P5,		
	/*UI_DISPLAY_SMART_WEATHER,*/                   UI_DISPLAY_SMART_WEATHER,	
	/*UI_DISPLAY_SMART_MESSAGE,*/                   UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_APP_NOTIF,*/                 UI_DISPLAY_SMART_APP_NOTIF,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/              UI_DISPLAY_SMART_DETAIL_NOTIF,
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/             UI_DISPLAY_SMART_INCOMING_CALL,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/          UI_DISPLAY_SMART_INCOMING_MESSAGE,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/      UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,*/        UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                UI_DISPLAY_SMART_IDLE_ALERT,
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/          UI_DISPLAY_SMART_HEART_RATE_ALERT,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/            UI_DISPLAY_SMART_STEP_10K_ALERT,		
	/*UI_DISPLAY_SMART_SOS_ALERT,*/                 UI_DISPLAY_SMART_SOS_ALERT,		
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/                 UI_DISPLAY_VITAL_SKIN_TEMP,		
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/                     UI_DISPLAY_SETTING_VER,
	// 6: Stopwatch
	/*UI_DISPLAY_STOPWATCH_START,*/                 UI_DISPLAY_STOPWATCH_START,	
	/*UI_DISPLAY_STOPWATCH_STOP,*/                  UI_DISPLAY_STOPWATCH_STOP,
	// 7: Workout mode
	/*UI_DISPLAY_WORKOUT_TREADMILL,*/               UI_DISPLAY_WORKOUT_TREADMILL,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                 UI_DISPLAY_WORKOUT_CYCLING,	
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                  UI_DISPLAY_WORKOUT_STAIRS,	
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/              UI_DISPLAY_WORKOUT_ELLIPTICAL,
	/*UI_DISPLAY_WORKOUT_ROW,*/                     UI_DISPLAY_WORKOUT_ROW,
	/*UI_DISPLAY_WORKOUT_AEROBIC,*/                 UI_DISPLAY_WORKOUT_AEROBIC,
	/*UI_DISPLAY_WORKOUT_PILOXING,*/                UI_DISPLAY_WORKOUT_PILOXING,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                  UI_DISPLAY_WORKOUT_OTHERS,
	/*UI_DISPLAY_WORKOUT_RT_READY,*/                UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_RT_TIME,*/                 UI_DISPLAY_WORKOUT_RT_TIME,
	/*UI_DISPLAY_WORKOUT_RT_HEART_RATE,*/           UI_DISPLAY_WORKOUT_RT_HEART_RATE,
	/*UI_DISPLAY_WORKOUT_RT_CALORIES,*/             UI_DISPLAY_WORKOUT_RT_CALORIES,
	/*UI_DISPLAY_WORKOUT_RT_END,*/                  UI_DISPLAY_WORKOUT_RT_END,
	// 8: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/           UI_DISPLAY_RUNNING_STAT_DISTANCE,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/               UI_DISPLAY_RUNNING_STAT_TIME,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/               UI_DISPLAY_RUNNING_STAT_PACE,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/             UI_DISPLAY_RUNNING_STAT_STRIDE,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/            UI_DISPLAY_RUNNING_STAT_CADENCE,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/         UI_DISPLAY_RUNNING_STAT_HEART_RATE,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/           UI_DISPLAY_RUNNING_STAT_CALORIES,
	// 9: training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/             UI_DISPLAY_TRAINING_STAT_START,
	/*UI_DISPLAY_TRAINING_STAT_START_OR_ANALYSIS,*/ UI_DISPLAY_TRAINING_STAT_READY,	
	/*UI_DISPLAY_TRAINING_STAT_READY,*/             UI_DISPLAY_TRAINING_STAT_READY,
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/              UI_DISPLAY_TRAINING_STAT_TIME,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/          UI_DISPLAY_TRAINING_STAT_DISTANCE,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/              UI_DISPLAY_TRAINING_STAT_PACE,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/        UI_DISPLAY_TRAINING_STAT_HEART_RATE,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/          UI_DISPLAY_TRAINING_STAT_RUN_STOP,
	// 10: CYCLING_OUTDOOR Statistics
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,*/       UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,		
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,*/   UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,*/ UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,*/       UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,	
	// 11: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/                      UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,
	/*UI_DISPLAY_CAROUSEL_2,*/                      UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_CAROUSEL_3,*/                      UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,
	// 12: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                         UI_DISPLAY_PREVIOUS,	
}; 

const I8U ui_matrix_finger_left[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                           UI_DISPLAY_HOME,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                  UI_DISPLAY_SYSTEM_RESTART,
	/*UI_DISPLAY_SYSTEM_OTA,*/                      UI_DISPLAY_SYSTEM_OTA,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                  UI_DISPLAY_SYSTEM_LINKING,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/             UI_DISPLAY_SYSTEM_UNAUTHORIZED,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/               UI_DISPLAY_SYSTEM_BATT_POWER,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                    UI_DISPLAY_TRACKER_STEP,  
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/             UI_DISPLAY_TRACKER_ACTIVE_TIME,	
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                     UI_DISPLAY_SMART_PM2P5,		
	/*UI_DISPLAY_SMART_WEATHER,*/                   UI_DISPLAY_SMART_WEATHER,	
	/*UI_DISPLAY_SMART_MESSAGE,*/                   UI_DISPLAY_CAROUSEL_2,
	/*UI_DISPLAY_SMART_APP_NOTIF,*/                 UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/              UI_DISPLAY_SMART_DETAIL_NOTIF,
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/             UI_DISPLAY_SMART_INCOMING_CALL,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/          UI_DISPLAY_SMART_INCOMING_MESSAGE,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/      UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,*/        UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                UI_DISPLAY_SMART_IDLE_ALERT,
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/          UI_DISPLAY_SMART_HEART_RATE_ALERT,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/            UI_DISPLAY_SMART_STEP_10K_ALERT,		
	/*UI_DISPLAY_SMART_SOS_ALERT,*/                 UI_DISPLAY_SMART_SOS_ALERT,		
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/                 UI_DISPLAY_VITAL_SKIN_TEMP,			
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/                     UI_DISPLAY_SETTING_VER,
	// 6: Stopwatch
	/*UI_DISPLAY_STOPWATCH_START,*/                 UI_DISPLAY_STOPWATCH_START,	
	/*UI_DISPLAY_STOPWATCH_STOP,*/                  UI_DISPLAY_STOPWATCH_STOP,
	// 7: Workout mode
	/*UI_DISPLAY_WORKOUT_TREADMILL,*/               UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                 UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                  UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/              UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_ROW,*/                     UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_AEROBIC,*/                 UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_PILOXING,*/                UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                  UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_WORKOUT_RT_READY,*/                UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_RT_TIME,*/                 UI_DISPLAY_WORKOUT_RT_TIME,
	/*UI_DISPLAY_WORKOUT_RT_HEART_RATE,*/           UI_DISPLAY_WORKOUT_RT_HEART_RATE,
	/*UI_DISPLAY_WORKOUT_RT_CALORIES,*/             UI_DISPLAY_WORKOUT_RT_CALORIES,
	/*UI_DISPLAY_WORKOUT_RT_END,*/                  UI_DISPLAY_WORKOUT_RT_END,
	// 8: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/           UI_DISPLAY_RUNNING_STAT_DISTANCE,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/               UI_DISPLAY_RUNNING_STAT_TIME,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/               UI_DISPLAY_RUNNING_STAT_PACE,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/             UI_DISPLAY_RUNNING_STAT_STRIDE,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/            UI_DISPLAY_RUNNING_STAT_CADENCE,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/         UI_DISPLAY_RUNNING_STAT_HEART_RATE,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/           UI_DISPLAY_RUNNING_STAT_CALORIES,
	// 9: training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/             UI_DISPLAY_TRAINING_STAT_START,
	/*UI_DISPLAY_TRAINING_STAT_START_OR_ANALYSIS,*/ UI_DISPLAY_TRAINING_STAT_START_OR_ANALYSIS,	
	/*UI_DISPLAY_TRAINING_STAT_READY,*/             UI_DISPLAY_TRAINING_STAT_READY,
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/              UI_DISPLAY_TRAINING_STAT_TIME,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/          UI_DISPLAY_TRAINING_STAT_DISTANCE,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/              UI_DISPLAY_TRAINING_STAT_PACE,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/        UI_DISPLAY_TRAINING_STAT_HEART_RATE,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/          UI_DISPLAY_TRAINING_STAT_RUN_STOP,
	// 10: CYCLING_OUTDOOR Statistics
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,*/       UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,		
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,*/   UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,*/ UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,*/       UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,	
	// 11: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/                      UI_DISPLAY_TRAINING_STAT_START,
	/*UI_DISPLAY_CAROUSEL_2,*/                      UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_CAROUSEL_3,*/                      UI_DISPLAY_SMART_PM2P5,
	// 12: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                         UI_DISPLAY_PREVIOUS,	
};

const I8U ui_matrix_finger_right[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                           UI_DISPLAY_HOME,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                  UI_DISPLAY_SYSTEM_RESTART,
	/*UI_DISPLAY_SYSTEM_OTA,*/                      UI_DISPLAY_SYSTEM_OTA,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                  UI_DISPLAY_SYSTEM_LINKING,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/             UI_DISPLAY_SYSTEM_UNAUTHORIZED,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/               UI_DISPLAY_SYSTEM_BATT_POWER,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                    UI_DISPLAY_TRACKER_STEP,  
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/             UI_DISPLAY_TRACKER_ACTIVE_TIME,		
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                     UI_DISPLAY_SMART_PM2P5,		
	/*UI_DISPLAY_SMART_WEATHER,*/                   UI_DISPLAY_SMART_WEATHER,	
	/*UI_DISPLAY_SMART_MESSAGE,*/                   UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_APP_NOTIF,*/                 UI_DISPLAY_SMART_APP_NOTIF,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/              UI_DISPLAY_SMART_DETAIL_NOTIF,
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/             UI_DISPLAY_SMART_INCOMING_CALL,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/          UI_DISPLAY_SMART_DETAIL_NOTIF,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/      UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,*/        UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                UI_DISPLAY_SMART_IDLE_ALERT,
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/          UI_DISPLAY_SMART_HEART_RATE_ALERT,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/            UI_DISPLAY_SMART_STEP_10K_ALERT,		
	/*UI_DISPLAY_SMART_SOS_ALERT,*/                 UI_DISPLAY_SMART_SOS_ALERT,		
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/                 UI_DISPLAY_VITAL_SKIN_TEMP,		
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/                     UI_DISPLAY_SETTING_VER,
	// 6: Stopwatch
	/*UI_DISPLAY_STOPWATCH_START,*/                 UI_DISPLAY_STOPWATCH_START,		
	/*UI_DISPLAY_STOPWATCH_STOP,*/                  UI_DISPLAY_CAROUSEL_2,
	// 7: Workout mode
	/*UI_DISPLAY_WORKOUT_TREADMILL,*/               UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                 UI_DISPLAY_WORKOUT_RT_READY,	
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                  UI_DISPLAY_WORKOUT_RT_READY,	
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/              UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_ROW,*/                     UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_AEROBIC,*/                 UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_PILOXING,*/                UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                  UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_RT_READY,*/                UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_RT_TIME,*/                 UI_DISPLAY_WORKOUT_RT_TIME,
	/*UI_DISPLAY_WORKOUT_RT_HEART_RATE,*/           UI_DISPLAY_WORKOUT_RT_HEART_RATE,
	/*UI_DISPLAY_WORKOUT_RT_CALORIES,*/             UI_DISPLAY_WORKOUT_RT_CALORIES,
	/*UI_DISPLAY_WORKOUT_RT_END,*/                  UI_DISPLAY_CAROUSEL_1,
	// 8: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/           UI_DISPLAY_RUNNING_STAT_DISTANCE,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/               UI_DISPLAY_RUNNING_STAT_TIME,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/               UI_DISPLAY_RUNNING_STAT_PACE,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/             UI_DISPLAY_RUNNING_STAT_STRIDE,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/            UI_DISPLAY_RUNNING_STAT_CADENCE,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/         UI_DISPLAY_RUNNING_STAT_HEART_RATE,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/           UI_DISPLAY_RUNNING_STAT_CALORIES,
	// 9: training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/             UI_DISPLAY_TRAINING_STAT_READY,
	/*UI_DISPLAY_TRAINING_STAT_START_OR_ANALYSIS,*/ UI_DISPLAY_RUNNING_STAT_DISTANCE,	
	/*UI_DISPLAY_TRAINING_STAT_READY,*/             UI_DISPLAY_TRAINING_STAT_READY,
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/              UI_DISPLAY_TRAINING_STAT_TIME,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/          UI_DISPLAY_TRAINING_STAT_DISTANCE,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/              UI_DISPLAY_TRAINING_STAT_PACE,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/        UI_DISPLAY_TRAINING_STAT_HEART_RATE,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/          UI_DISPLAY_CAROUSEL_1,
	// 10: CYCLING_OUTDOOR Statistics
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,*/       UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,		
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,*/   UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,*/ UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,*/   UI_DISPLAY_CAROUSEL_1,	
	// 11: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/                      UI_DISPLAY_WORKOUT_TREADMILL,
	/*UI_DISPLAY_CAROUSEL_2,*/                      UI_DISPLAY_SMART_WEATHER,
	/*UI_DISPLAY_CAROUSEL_3,*/                      UI_DISPLAY_SETTING_VER,
	// 12: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                         UI_DISPLAY_PREVIOUS,	
};

const I8U ui_matrix_swipe_left[UI_DISPLAY_MAXIMUM] = {
	// 0: Home 
	/* UI_DISPLAY_HOME */                           UI_DISPLAY_TRACKER_STEP,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                  UI_DISPLAY_SYSTEM_RESTART,
	/*UI_DISPLAY_SYSTEM_OTA,*/                      UI_DISPLAY_SYSTEM_OTA,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                  UI_DISPLAY_SYSTEM_LINKING,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/             UI_DISPLAY_SYSTEM_UNAUTHORIZED,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/               UI_DISPLAY_SYSTEM_BATT_POWER,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                    UI_DISPLAY_TRACKER_DISTANCE,  
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                UI_DISPLAY_TRACKER_ACTIVE_TIME,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/             UI_DISPLAY_VITAL_HEART_RATE,		
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                     UI_DISPLAY_CAROUSEL_3,		
	/*UI_DISPLAY_SMART_WEATHER,*/                   UI_DISPLAY_CAROUSEL_2,	
	/*UI_DISPLAY_SMART_MESSAGE,*/                   UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_APP_NOTIF,*/                 UI_DISPLAY_SMART_APP_NOTIF,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/              UI_DISPLAY_SMART_DETAIL_NOTIF,
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/             UI_DISPLAY_SMART_INCOMING_CALL,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/          UI_DISPLAY_SMART_INCOMING_MESSAGE,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/      UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,*/        UI_DISPLAY_CAROUSEL_3,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                UI_DISPLAY_SMART_IDLE_ALERT,
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/          UI_DISPLAY_SMART_HEART_RATE_ALERT,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/            UI_DISPLAY_SMART_STEP_10K_ALERT,	
	/*UI_DISPLAY_SMART_SOS_ALERT,*/                 UI_DISPLAY_SMART_SOS_ALERT,		
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/                 UI_DISPLAY_HOME,			
	// 5: Special back panel mode 
	/*UI_DISPLAY_SETTING_VER,*/                     UI_DISPLAY_CAROUSEL_3,
	// 6: Stopwatch
	/*UI_DISPLAY_STOPWATCH_START,*/                 UI_DISPLAY_STOPWATCH_STOP,	
	/*UI_DISPLAY_STOPWATCH_STOP,*/                  UI_DISPLAY_STOPWATCH_START,
	// 7: Workout mode   
	/*UI_DISPLAY_WORKOUT_TREADMILL,*/               UI_DISPLAY_WORKOUT_CYCLING,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                 UI_DISPLAY_WORKOUT_STAIRS,	
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                  UI_DISPLAY_WORKOUT_ELLIPTICAL,	
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/              UI_DISPLAY_WORKOUT_ROW,
	/*UI_DISPLAY_WORKOUT_ROW,*/                     UI_DISPLAY_WORKOUT_AEROBIC,
	/*UI_DISPLAY_WORKOUT_AEROBIC,*/                 UI_DISPLAY_WORKOUT_PILOXING,
	/*UI_DISPLAY_WORKOUT_PILOXING,*/                UI_DISPLAY_WORKOUT_OTHERS,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                  UI_DISPLAY_WORKOUT_TREADMILL,	
	/*UI_DISPLAY_WORKOUT_RT_READY,*/                UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_RT_TIME,*/                 UI_DISPLAY_WORKOUT_RT_HEART_RATE,
	/*UI_DISPLAY_WORKOUT_RT_HEART_RATE,*/           UI_DISPLAY_WORKOUT_RT_CALORIES,
	/*UI_DISPLAY_WORKOUT_RT_CALORIES,*/             UI_DISPLAY_WORKOUT_RT_END,
	/*UI_DISPLAY_WORKOUT_RT_END,*/                  UI_DISPLAY_WORKOUT_RT_TIME,
	// 8: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/           UI_DISPLAY_RUNNING_STAT_TIME,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/               UI_DISPLAY_RUNNING_STAT_PACE,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/               UI_DISPLAY_RUNNING_STAT_STRIDE,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/             UI_DISPLAY_RUNNING_STAT_CADENCE,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/            UI_DISPLAY_RUNNING_STAT_HEART_RATE,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/         UI_DISPLAY_RUNNING_STAT_CALORIES,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/           UI_DISPLAY_RUNNING_STAT_DISTANCE,
	// 9: training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/             UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_TRAINING_STAT_START_OR_ANALYSIS,*/ UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_TRAINING_STAT_READY,*/             UI_DISPLAY_TRAINING_STAT_READY,
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/              UI_DISPLAY_TRAINING_STAT_DISTANCE,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/          UI_DISPLAY_TRAINING_STAT_PACE,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/              UI_DISPLAY_TRAINING_STAT_HEART_RATE,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/        UI_DISPLAY_TRAINING_STAT_RUN_STOP,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/          UI_DISPLAY_TRAINING_STAT_TIME,
	// 10: CYCLING_OUTDOOR Statistics
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,*/      UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,*/       UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,		
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,*/   UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,*/ UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,*/   UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,	
	// 11: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/                      UI_DISPLAY_CAROUSEL_2,
	/*UI_DISPLAY_CAROUSEL_2,*/                      UI_DISPLAY_CAROUSEL_3,
	/*UI_DISPLAY_CAROUSEL_3,*/                      UI_DISPLAY_CAROUSEL_1,
	// 12: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                         UI_DISPLAY_PREVIOUS,	
};

const I8U ui_matrix_swipe_right[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                           UI_DISPLAY_VITAL_SKIN_TEMP,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                  UI_DISPLAY_SYSTEM_RESTART,
	/*UI_DISPLAY_SYSTEM_OTA,*/                      UI_DISPLAY_SYSTEM_OTA,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                  UI_DISPLAY_SYSTEM_LINKING,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/             UI_DISPLAY_SYSTEM_UNAUTHORIZED,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/               UI_DISPLAY_SYSTEM_BATT_POWER,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                    UI_DISPLAY_HOME,  
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                UI_DISPLAY_TRACKER_STEP,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/             UI_DISPLAY_TRACKER_CALORIES,	
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                     UI_DISPLAY_CAROUSEL_3,		
	/*UI_DISPLAY_SMART_WEATHER,*/                   UI_DISPLAY_CAROUSEL_2,	
	/*UI_DISPLAY_SMART_MESSAGE,*/                   UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_APP_NOTIF,*/                 UI_DISPLAY_SMART_APP_NOTIF,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/              UI_DISPLAY_SMART_DETAIL_NOTIF,
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/             UI_DISPLAY_SMART_INCOMING_CALL,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/          UI_DISPLAY_SMART_INCOMING_MESSAGE,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/      UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,*/        UI_DISPLAY_CAROUSEL_3,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                UI_DISPLAY_SMART_IDLE_ALERT,
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/          UI_DISPLAY_SMART_HEART_RATE_ALERT,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/            UI_DISPLAY_SMART_STEP_10K_ALERT,	
	/*UI_DISPLAY_SMART_SOS_ALERT,*/                 UI_DISPLAY_SMART_SOS_ALERT,		
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                UI_DISPLAY_TRACKER_ACTIVE_TIME,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/                 UI_DISPLAY_VITAL_HEART_RATE,			
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/                     UI_DISPLAY_CAROUSEL_3,
	// 6: Stopwatch
	/*UI_DISPLAY_STOPWATCH_START,*/                 UI_DISPLAY_STOPWATCH_STOP,			
	/*UI_DISPLAY_STOPWATCH_STOP,*/                  UI_DISPLAY_STOPWATCH_START,
	// 7: Workout mode
	/*UI_FRAME_PAGE_WORKOUT_TREADMILL,*/            UI_DISPLAY_WORKOUT_OTHERS,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                 UI_DISPLAY_WORKOUT_TREADMILL,	
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                  UI_DISPLAY_WORKOUT_CYCLING,	
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/              UI_DISPLAY_WORKOUT_STAIRS,
	/*UI_DISPLAY_WORKOUT_ROW,*/                     UI_DISPLAY_WORKOUT_ELLIPTICAL,
	/*UI_DISPLAY_WORKOUT_AEROBIC,*/                 UI_DISPLAY_WORKOUT_ROW,
	/*UI_DISPLAY_WORKOUT_PILOXING,*/                UI_DISPLAY_WORKOUT_AEROBIC,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                  UI_DISPLAY_WORKOUT_PILOXING,	
	/*UI_DISPLAY_WORKOUT_RT_READY,*/                UI_DISPLAY_WORKOUT_RT_READY,
	/*UI_DISPLAY_WORKOUT_RT_TIME,*/                 UI_DISPLAY_WORKOUT_RT_END,
	/*UI_DISPLAY_WORKOUT_RT_HEART_RATE,*/           UI_DISPLAY_WORKOUT_RT_TIME,
	/*UI_DISPLAY_WORKOUT_RT_CALORIES,*/             UI_DISPLAY_WORKOUT_RT_HEART_RATE,
	/*UI_DISPLAY_WORKOUT_RT_END,*/                  UI_DISPLAY_WORKOUT_RT_CALORIES,
	// 8: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/           UI_DISPLAY_RUNNING_STAT_CALORIES,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/               UI_DISPLAY_RUNNING_STAT_DISTANCE,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/               UI_DISPLAY_RUNNING_STAT_TIME,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/             UI_DISPLAY_RUNNING_STAT_PACE,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/            UI_DISPLAY_RUNNING_STAT_STRIDE,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/         UI_DISPLAY_RUNNING_STAT_CADENCE,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/           UI_DISPLAY_RUNNING_STAT_HEART_RATE,
	// 9: training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/             UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_TRAINING_STAT_START_OR_ANALYSIS,*/ UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_TRAINING_STAT_READY,*/             UI_DISPLAY_TRAINING_STAT_READY,
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/              UI_DISPLAY_TRAINING_STAT_RUN_STOP,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/          UI_DISPLAY_TRAINING_STAT_TIME,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/              UI_DISPLAY_TRAINING_STAT_DISTANCE,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/        UI_DISPLAY_TRAINING_STAT_PACE,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/          UI_DISPLAY_TRAINING_STAT_HEART_RATE,
	// 10: CYCLING_OUTDOOR Statistics
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,*/      UI_DISPLAY_CAROUSEL_1,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,*/       UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,		
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,*/   UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,*/      UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,*/ UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,*/   UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,	
	// 11: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/                      UI_DISPLAY_CAROUSEL_3,
	/*UI_DISPLAY_CAROUSEL_2,*/                      UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_CAROUSEL_3,*/                      UI_DISPLAY_CAROUSEL_2,
	// 12: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                         UI_DISPLAY_PREVIOUS,	
};

//
// UI FRAME GESTURE (UFG) constrains
//
#define UFG_NONE                                  0x00
#define UFG_SWIPE_PANNING                         0x01
#define UFG_FINGER_IRIS                           0x02
#define UFG_BUTTON_SINGLE                         0x04
#define UFG_BUTTON_HOLD                           0x08

#define S_F_BS_BH (UFG_SWIPE_PANNING | UFG_FINGER_IRIS | UFG_BUTTON_SINGLE | UFG_BUTTON_HOLD)
#define F_BS (UFG_FINGER_IRIS | UFG_BUTTON_SINGLE)
#define F_BS_BH (UFG_FINGER_IRIS | UFG_BUTTON_SINGLE | UFG_BUTTON_HOLD)
#define N_F (UFG_NONE | UFG_FINGER_IRIS)
#define S_F_BS (UFG_SWIPE_PANNING | UFG_FINGER_IRIS | UFG_BUTTON_SINGLE)
#define S_F (UFG_SWIPE_PANNING | UFG_FINGER_IRIS)

const I8U ui_gesture_constrain[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                          S_F_BS_BH,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                 N_F,
	/*UI_DISPLAY_SYSTEM_OTA,*/                     N_F,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                 N_F,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/            N_F,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/              N_F,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                   S_F_BS_BH,  
	/*UI_DISPLAY_TRACKER_DISTANCE,*/               S_F_BS_BH,
	/*UI_DISPLAY_TRACKER_CALORIES,*/               S_F_BS_BH,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/            S_F_BS_BH,				
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                    S_F_BS_BH,		
	/*UI_DISPLAY_SMART_WEATHER,*/                  S_F_BS_BH,	
	/*UI_DISPLAY_SMART_MESSAGE,*/                  F_BS,
	/*UI_DISPLAY_SMART_APP_NOTIF,*/                S_F_BS_BH,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/             S_F_BS_BH,
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/            F_BS,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/         F_BS,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/     S_F_BS_BH,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,*/       S_F_BS_BH,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/               S_F_BS_BH,
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/         S_F_BS_BH,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/           S_F_BS_BH,		
	/*UI_DISPLAY_SMART_SOS_ALERT,*/                N_F,		
	// 4: a set of VITAL  
	/*UI_DISPLAY_VITAL_HEART_RATE,*/               S_F_BS_BH,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/                S_F_BS_BH,		
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/                    S_F_BS_BH,
	// 6: Stopwatch
	/*UI_DISPLAY_STOPWATCH_START,*/                S_F_BS_BH,		
	/*UI_DISPLAY_STOPWATCH_STOP,*/                 S_F_BS_BH,
	// 7: Workout mode  
	/*UI_DISPLAY_WORKOUT_TREADMILL,*/              S_F_BS_BH,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                S_F_BS_BH,	
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                 S_F_BS_BH,	
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/             S_F_BS_BH,
	/*UI_DISPLAY_WORKOUT_ROW,*/                    S_F_BS_BH,
	/*UI_DISPLAY_WORKOUT_AEROBIC,*/                S_F_BS_BH,
	/*UI_DISPLAY_WORKOUT_PILOXING,*/               S_F_BS_BH,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                 S_F_BS_BH,	
	/*UI_DISPLAY_WORKOUT_RT_READY,*/               N_F,
	/*UI_DISPLAY_WORKOUT_RT_TIME,*/                S_F_BS_BH,
	/*UI_DISPLAY_WORKOUT_RT_HEART_RATE,*/          S_F_BS_BH,
	/*UI_DISPLAY_WORKOUT_RT_CALORIES,*/            S_F_BS_BH,
	/*UI_DISPLAY_WORKOUT_RT_END,*/                 S_F_BS_BH,
	// 8: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/          S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/              S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/              S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/            S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/           S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/        S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/          S_F_BS_BH,
	// 9: training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/            S_F_BS_BH,
	/*UI_DISPLAY_TRAINING_STAT_START_OR_ANALYSIS,*/S_F_BS_BH,	
	/*UI_DISPLAY_TRAINING_STAT_READY,*/            N_F,
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/             S_F_BS_BH,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/         S_F_BS_BH,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/             S_F_BS_BH,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/       S_F_BS_BH,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/         S_F_BS_BH,
	// 10: CYCLING_OUTDOOR Statistics
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,*/     S_F_BS_BH,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,*/     N_F,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,*/      S_F_BS_BH,		
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,*/  S_F_BS_BH,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,*/     S_F_BS_BH,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,*/S_F_BS_BH,	
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,*/  S_F_BS_BH,	
	// 11: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/                     S_F_BS_BH,
	/*UI_DISPLAY_CAROUSEL_2,*/                     S_F_BS_BH,
	/*UI_DISPLAY_CAROUSEL_3,*/                     S_F_BS_BH,	
	// 12: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                        S_F_BS_BH,		
};

const I16U ui_matrix_blinking_interval[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                          400,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                 1000,
	/*UI_DISPLAY_SYSTEM_OTA,*/                     1000,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                 400,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/            2000,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/              1000,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                   400,  
	/*UI_DISPLAY_TRACKER_DISTANCE,*/               400,
	/*UI_DISPLAY_TRACKER_CALORIES,*/               400,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/            400,			
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                    400,		
	/*UI_DISPLAY_SMART_WEATHER,*/                  400,	
	/*UI_DISPLAY_SMART_MESSAGE,*/                  2000,
	/*UI_DISPLAY_SMART_APP_NOTIF,*/                2000,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/             2000,
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/            400,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/         400,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/     400,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_DETAIL,*/       2000,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/               400,
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/         400,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/           400,			
	/*UI_DISPLAY_SMART_SOS_ALERT,*/                1000,			
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/               333,//400,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/                400,			
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/                    400,
	// 6: Stopwatch
	/*UI_DISPLAY_STOPWATCH_START,*/                0,		
	/*UI_DISPLAY_STOPWATCH_STOP,*/                 2000,
	// 7: Workout mode
	/*UI_DISPLAY_WORKOUT_TREADMILL,*/              2000,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                2000,	
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                 2000,	
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/             2000,
	/*UI_DISPLAY_WORKOUT_ROW,*/                    2000,
	/*UI_DISPLAY_WORKOUT_AEROBIC,*/                2000,
	/*UI_DISPLAY_WORKOUT_PILOXING,*/               2000,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                 2000,	
	/*UI_DISPLAY_WORKOUT_RT_READY,*/               100,
	/*UI_DISPLAY_WORKOUT_RT_TIME,*/                333,//300,
	/*UI_DISPLAY_WORKOUT_RT_HEART_RATE,*/          333,//300,
	/*UI_DISPLAY_WORKOUT_RT_CALORIES,*/            333,//300,
	/*UI_DISPLAY_WORKOUT_RT_END,*/                 333,//400,
	// 8: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/          2000,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/              2000,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/              2000,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/            2000,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/           2000,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/        2000,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/          2000,
	// 9: training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/            400,
	/*UI_DISPLAY_TRAINING_STAT_START_OR_ANALYSIS,*/400,	
	/*UI_DISPLAY_TRAINING_STAT_READY,*/            100,
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/             333,//300,
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/         333,//300,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/             333,//300,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/       333,//300,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/         333,//400,
	// 10: CYCLING_OUTDOOR Statistics
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_START,*/     400,
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_READY,*/     100,
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_TIME,*/      333,//300,
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_DISTANCE,*/  333,//300,
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_SPEED,*/     333,//300,
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_HEART_RATE,*/333,//300,
	/*UI_DISPLAY_CYCLING_OUTDOOR_STAT_STOP,*/      333,//400,
	// 11: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/                     2000,
	/*UI_DISPLAY_CAROUSEL_2,*/                     2000,
	/*UI_DISPLAY_CAROUSEL_3,*/                     2000,
	// 12: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                        2000,	
};
