#include "main.h"

const I8U ui_matrix_button_single[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                             UI_DISPLAY_TRACKER_STEP,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                    UI_DISPLAY_SYSTEM_RESTART,
	/*UI_DISPLAY_SYSTEM_OTA,*/                        UI_DISPLAY_SYSTEM_OTA,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                    UI_DISPLAY_SYSTEM_LINKING,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/               UI_DISPLAY_SYSTEM_UNAUTHORIZED,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/                 UI_DISPLAY_SYSTEM_BATT_POWER,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                      UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                  UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                  UI_DISPLAY_TRACKER_ACTIVE_TIME,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/               UI_DISPLAY_VITAL_HEART_RATE,  	
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                       UI_DISPLAY_TRAINING_STAT_START,
	/*UI_DISPLAY_SMART_WEATHER,*/                     UI_DISPLAY_SMART_PM2P5,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/                UI_DISPLAY_SMART_DETAIL_NOTIF,	
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/               UI_DISPLAY_SMART_INCOMING_CALL,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/            UI_DISPLAY_SMART_DETAIL_NOTIF,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/        UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                  UI_DISPLAY_SMART_IDLE_ALERT,	
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/            UI_DISPLAY_SMART_HEART_RATE_ALERT,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/              UI_DISPLAY_SMART_STEP_10K_ALERT,		
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                  UI_DISPLAY_SMART_WEATHER,
	// 5: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_RUN_ANALYSIS,*/         UI_DISPLAY_HOME,	
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/             UI_DISPLAY_RUNNING_STAT_TIME,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/                 UI_DISPLAY_RUNNING_STAT_PACE,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/                 UI_DISPLAY_RUNNING_STAT_STRIDE,   
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/               UI_DISPLAY_RUNNING_STAT_CADENCE,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/              UI_DISPLAY_RUNNING_STAT_HEART_RATE,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/           UI_DISPLAY_RUNNING_STAT_CALORIES,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/             UI_DISPLAY_RUNNING_STAT_STOP_ANALYSIS,
	/*UI_DISPLAY_RUNNING_STAT_STOP_ANALYSIS,*/        UI_DISPLAY_RUNNING_STAT_DISTANCE,		
	// 6: Training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/               UI_DISPLAY_RUNNING_STAT_RUN_ANALYSIS,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS,*/         UI_DISPLAY_TRAINING_STAT_CONNECT_GPS,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_TIMEOUT,*/ UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_TIMEOUT,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_FAIL,*/    UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_FAIL,			
	/*UI_DISPLAY_TRAINING_STAT_READY,*/               UI_DISPLAY_TRAINING_STAT_READY,	
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/                UI_DISPLAY_TRAINING_STAT_DISTANCE,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/            UI_DISPLAY_TRAINING_STAT_PACE,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/                UI_DISPLAY_TRAINING_STAT_HEART_RATE,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/          UI_DISPLAY_TRAINING_STAT_RUN_STOP,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/            UI_DISPLAY_TRAINING_STAT_TIME,	
	// 7: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                           UI_DISPLAY_PREVIOUS,
};

const I8U ui_matrix_button_hold[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                             UI_DISPLAY_TRACKER_STEP,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                    UI_DISPLAY_SYSTEM_RESTART,
	/*UI_DISPLAY_SYSTEM_OTA,*/                        UI_DISPLAY_SYSTEM_OTA,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                    UI_DISPLAY_SYSTEM_LINKING,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/               UI_DISPLAY_SYSTEM_UNAUTHORIZED,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/                 UI_DISPLAY_SYSTEM_BATT_POWER,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                      UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                  UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                  UI_DISPLAY_TRACKER_ACTIVE_TIME,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/               UI_DISPLAY_VITAL_HEART_RATE,  	
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                       UI_DISPLAY_TRAINING_STAT_START,
	/*UI_DISPLAY_SMART_WEATHER,*/                     UI_DISPLAY_SMART_PM2P5,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/                UI_DISPLAY_SMART_DETAIL_NOTIF,	
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/               UI_DISPLAY_SMART_INCOMING_CALL,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/            UI_DISPLAY_SMART_DETAIL_NOTIF,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/        UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,	
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                  UI_DISPLAY_SMART_IDLE_ALERT,	
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/            UI_DISPLAY_SMART_HEART_RATE_ALERT,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/              UI_DISPLAY_SMART_STEP_10K_ALERT,			
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                  UI_DISPLAY_SMART_WEATHER,
	// 5: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_RUN_ANALYSIS,*/         UI_DISPLAY_RUNNING_STAT_DISTANCE,		
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/             UI_DISPLAY_RUNNING_STAT_TIME,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/                 UI_DISPLAY_RUNNING_STAT_PACE,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/                 UI_DISPLAY_RUNNING_STAT_STRIDE,   
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/               UI_DISPLAY_RUNNING_STAT_CADENCE,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/              UI_DISPLAY_RUNNING_STAT_HEART_RATE,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/           UI_DISPLAY_RUNNING_STAT_CALORIES,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/             UI_DISPLAY_RUNNING_STAT_STOP_ANALYSIS,
	/*UI_DISPLAY_RUNNING_STAT_STOP_ANALYSIS,*/        UI_DISPLAY_HOME,	
	// 6: Training Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/               UI_DISPLAY_TRAINING_STAT_CONNECT_GPS,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS,*/         UI_DISPLAY_TRAINING_STAT_CONNECT_GPS,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_TIMEOUT,*/ UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_TIMEOUT,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_FAIL,*/    UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_FAIL,			
	/*UI_DISPLAY_TRAINING_STAT_READY,*/               UI_DISPLAY_TRAINING_STAT_READY,	
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/                UI_DISPLAY_TRAINING_STAT_DISTANCE,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/            UI_DISPLAY_TRAINING_STAT_PACE,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/                UI_DISPLAY_TRAINING_STAT_HEART_RATE,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/          UI_DISPLAY_TRAINING_STAT_RUN_STOP,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/            UI_DISPLAY_RUNNING_STAT_RUN_ANALYSIS,		
	// 7: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                           UI_DISPLAY_PREVIOUS,
};

//
// UI FRAME GESTURE (UFG) constrains
//
#define UFG_NONE                                    0x00
#define UFG_SWIPE_PANNING                           0x01
#define UFG_FINGER_IRIS                             0x02
#define UFG_BUTTON_SINGLE                           0x04
#define UFG_BUTTON_HOLD                             0x08

#define S_F_BS_BH (UFG_SWIPE_PANNING | UFG_FINGER_IRIS | UFG_BUTTON_SINGLE | UFG_BUTTON_HOLD)
#define F_BS (UFG_FINGER_IRIS | UFG_BUTTON_SINGLE)
#define F_BS_BH (UFG_FINGER_IRIS | UFG_BUTTON_SINGLE | UFG_BUTTON_HOLD)
#define N_F (UFG_NONE | UFG_FINGER_IRIS)
#define S_F_BS (UFG_SWIPE_PANNING | UFG_FINGER_IRIS | UFG_BUTTON_SINGLE)
#define S_F (UFG_SWIPE_PANNING | UFG_FINGER_IRIS)

const I8U ui_gesture_constrain[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                              S_F_BS_BH,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                     N_F,
	/*UI_DISPLAY_SYSTEM_OTA,*/                         N_F,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                     N_F,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/                N_F,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/                  N_F,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                       S_F_BS_BH,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                   S_F_BS_BH,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                   S_F_BS_BH,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/                S_F_BS_BH,  	
	// 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                        S_F_BS_BH,
	/*UI_DISPLAY_SMART_WEATHER,*/                      S_F_BS_BH,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/                 S_F_BS_BH,	
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/                S_F_BS_BH,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/             S_F_BS_BH,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/         S_F_BS_BH,		
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                   S_F_BS_BH,		
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/             S_F_BS_BH,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/               S_F_BS_BH,				
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                   S_F_BS_BH,
	// 5: Running Statistics      
	/*UI_DISPLAY_RUNNING_STAT_RUN_ANALYSIS,*/          S_F_BS_BH,			
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/              S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/                  S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/                  S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/                S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/               S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/            S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/              S_F_BS_BH,
	/*UI_DISPLAY_RUNNING_STAT_STOP_ANALYSIS,*/         S_F_BS_BH,		
	// 6: Running Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/                S_F_BS_BH,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS,*/          N_F,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_TIMEOUT,*/  N_F,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_FAIL,*/     N_F,			
	/*UI_DISPLAY_TRAINING_STAT_READY,*/                N_F,		
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/                 S_F_BS_BH,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/             S_F_BS_BH,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/                 S_F_BS_BH,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/           S_F_BS_BH,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/             S_F_BS_BH,			
	// 7: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                            S_F_BS_BH,
};

const I16U ui_matrix_blinking_interval[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                              400,
	// 1: System
	/*UI_DISPLAY_SYSTEM_RESTART,*/                     1000,
	/*UI_DISPLAY_SYSTEM_OTA,*/                         1000,
	/*UI_DISPLAY_SYSTEM_LINKING,*/                     400,
	/*UI_DISPLAY_SYSTEM_UNAUTHORIZED,*/                2000,		
	/*UI_DISPLAY_SYSTEM_BATT_POWER,*/                  1000,	
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_STEP,*/                       400,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/                   400,
	/*UI_DISPLAY_TRACKER_CALORIES,*/                   400,
	/*UI_DISPLAY_TRACKER_ACTIVE_TIME,*/                400,  	
  // 3: a set of smart features
	/*UI_DISPLAY_SMART_PM2P5,*/                        400,
	/*UI_DISPLAY_SMART_WEATHER,*/                      400,
	/*UI_DISPLAY_SMART_DETAIL_NOTIF,*/                 2000,	
	/*UI_DISPLAY_SMART_INCOMING_CALL,*/                400,
	/*UI_DISPLAY_SMART_INCOMING_MESSAGE,*/             400,
	/*UI_DISPLAY_SMART_ALARM_CLOCK_REMINDER,*/         400,		
	/*UI_DISPLAY_SMART_IDLE_ALERT,*/                   400,		
	/*UI_DISPLAY_SMART_HEART_RATE_ALERT,*/             400,	
	/*UI_DISPLAY_SMART_STEP_10K_ALERT,*/               400,				
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/                   333,//400,
	// 5: Running Statistics
	/*UI_DISPLAY_RUNNING_STAT_RUN_ANALYSIS,*/          2000,			
	/*UI_DISPLAY_RUNNING_STAT_DISTANCE,*/              2000,
	/*UI_DISPLAY_RUNNING_STAT_TIME,*/                  2000,
	/*UI_DISPLAY_RUNNING_STAT_PACE,*/                  2000,
	/*UI_DISPLAY_RUNNING_STAT_STRIDE,*/                2000,
	/*UI_DISPLAY_RUNNING_STAT_CADENCE,*/               2000,
	/*UI_DISPLAY_RUNNING_STAT_HEART_RATE,*/            2000,
	/*UI_DISPLAY_RUNNING_STAT_CALORIES,*/              2000,
	/*UI_DISPLAY_RUNNING_STAT_STOP_ANALYSIS,*/         2000,		
	// 6: Running Statistics
	/*UI_DISPLAY_TRAINING_STAT_START,*/                400,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS,*/          400,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_TIMEOUT,*/  400,		
	/*UI_DISPLAY_TRAINING_STAT_CONNECT_GPS_FAIL,*/     400,				
	/*UI_DISPLAY_TRAINING_STAT_READY,*/                100,		
	/*UI_DISPLAY_TRAINING_STAT_TIME,*/                 300,	
	/*UI_DISPLAY_TRAINING_STAT_DISTANCE,*/             300,
	/*UI_DISPLAY_TRAINING_STAT_PACE,*/                 300,
	/*UI_DISPLAY_TRAINING_STAT_HEART_RATE,*/           333,//300,
	/*UI_DISPLAY_TRAINING_STAT_RUN_STOP,*/             400,		
	// 7: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                            400,
};
