#include "main.h"

const I8U ui_matrix_button[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                 UI_DISPLAY_VITAL_HEART_RATE,
	// 1: System
	/*UI_DISPLAY_DARK,*/                  UI_DISPLAY_DARK,
	/*UI_DISPLAY_CLING,*/                UI_DISPLAY_CLING,
	/*UI_DISPLAY_OTA,*/                    UI_DISPLAY_OTA,
	/*UI_DISPLAY_PAIRING,*/               UI_DISPLAY_PAIRING,
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_UV_IDX,*/        UI_DISPLAY_SMART_WEATHER,
	/*UI_DISPLAY_TRACKER_STEP,*/          UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_SLEEP,*/UI_DISPLAY_TRACKER_STEP,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/UI_DISPLAY_TRACKER_UV_IDX,
	/*UI_DISPLAY_TRACKER_CALORIES,*/UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_MINUTES,*/UI_DISPLAY_TRACKER_MINUTES,
	/*UI_DISPLAY_TRACKER_CLOCK,*/UI_DISPLAY_TRACKER_CLOCK,
	/*UI_DISPLAY_TRACKER_NAME,*/UI_DISPLAY_TRACKER_NAME,
	// 3: a set of battery stats
	/*UI_DISPLAY_SMART_CALL,*/UI_DISPLAY_SMART_CALL,
	/*UI_DISPLAY_SMART_MESSAGE,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_SMART_PHONE_FINDER,*/UI_DISPLAY_SMART_PHONE_FINDER,
	/*UI_DISPLAY_SMART_REMINDER,*/UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_SMART_WEATHER,*/UI_DISPLAY_SMART_MESSAGE,
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/UI_DISPLAY_TRACKER_SLEEP,
	/*UI_DISPLAY_VITAL_ACTIVE,*/UI_DISPLAY_VITAL_ACTIVE,
	/*UI_DISPLAY_VITAL_SUSPEND,*/UI_DISPLAY_VITAL_SUSPEND,
	/*UI_DISPLAY_VITAL_ENUM,*/UI_DISPLAY_VITAL_ENUM,
	/*UI_DISPLAY_VITAL_ERROR,*/UI_DISPLAY_VITAL_ERROR,
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/UI_DISPLAY_SETTING_VER,
	// 6: Confirmation messages
	/*UI_DISPLAY_STOPWATCH_START,*/ UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_STOPWATCH_STOP,*/UI_DISPLAY_STOPWATCH_STOP,
	/*UI_DISPLAY_STOPWATCH_HEARTRATE,*/UI_DISPLAY_STOPWATCH_HEARTRATE,
	/*UI_DISPLAY_STOPWATCH_CALORIES,*/UI_DISPLAY_STOPWATCH_CALORIES,
	/*UI_DISPLAY_STOPWATCH_RESULT,*/UI_DISPLAY_STOPWATCH_RESULT,
	// 7: Info menu
	/*UI_DISPLAY_WORKOUT_WALKING,*/                  UI_DISPLAY_WORKOUT_INDOOR ,
	/*UI_DISPLAY_WORKOUT_RUNNING,*/                  UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_ROW,*/                  UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/                 UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                 UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                 UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_SWIMING,*/                 UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                 UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_INDOOR,*/                    UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_WORKOUT_OUTDOOR,*/                    UI_DISPLAY_STOPWATCH_START,
	// 9: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/UI_DISPLAY_CAROUSEL_2,
	/*UI_DISPLAY_CAROUSEL_2,*/UI_DISPLAY_CAROUSEL_3,
	/*UI_DISPLAY_CAROUSEL_3,*/UI_DISPLAY_CAROUSEL_4,
	/*UI_DISPLAY_CAROUSEL_4,*/UI_DISPLAY_CAROUSEL_5,
	/*UI_DISPLAY_CAROUSEL_5,*/UI_DISPLAY_CAROUSEL_1,
	// 10: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/UI_DISPLAY_PREVIOUS,
};

const I8U ui_matrix_finger_down[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                 UI_DISPLAY_HOME,
	// 1: System
	/*UI_DISPLAY_DARK,*/                  UI_DISPLAY_DARK,
	/*UI_DISPLAY_CLING,*/                UI_DISPLAY_CLING,
	/*UI_DISPLAY_OTA,*/                    UI_DISPLAY_OTA,
	/*UI_DISPLAY_PAIRING,*/               UI_DISPLAY_PAIRING,
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_UV_IDX,*/        UI_DISPLAY_TRACKER_UV_IDX,
	/*UI_DISPLAY_TRACKER_STEP,*/          UI_DISPLAY_TRACKER_STEP,
	/*UI_DISPLAY_TRACKER_SLEEP,*/UI_DISPLAY_TRACKER_SLEEP,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_CALORIES,*/UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_MINUTES,*/UI_DISPLAY_TRACKER_MINUTES,
	/*UI_DISPLAY_TRACKER_CLOCK,*/UI_DISPLAY_TRACKER_CLOCK,
	/*UI_DISPLAY_TRACKER_NAME,*/UI_DISPLAY_TRACKER_NAME,
	// 3: a set of battery stats
	/*UI_DISPLAY_SMART_CALL,*/UI_DISPLAY_SMART_CALL,
	/*UI_DISPLAY_SMART_MESSAGE,*/UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_PHONE_FINDER,*/UI_DISPLAY_SMART_PHONE_FINDER,
	/*UI_DISPLAY_SMART_REMINDER,*/UI_DISPLAY_SMART_REMINDER,
	/*UI_DISPLAY_SMART_WEATHER,*/UI_DISPLAY_SMART_WEATHER,
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_VITAL_ACTIVE,*/UI_DISPLAY_VITAL_ACTIVE,
	/*UI_DISPLAY_VITAL_SUSPEND,*/UI_DISPLAY_VITAL_SUSPEND,
	/*UI_DISPLAY_VITAL_ENUM,*/UI_DISPLAY_VITAL_ENUM,
	/*UI_DISPLAY_VITAL_ERROR,*/UI_DISPLAY_VITAL_ERROR,
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/UI_DISPLAY_SETTING_VER,
	// 6: Confirmation messages
	/*UI_DISPLAY_STOPWATCH_START,*/ UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_STOPWATCH_STOP,*/UI_DISPLAY_STOPWATCH_STOP,
	/*UI_DISPLAY_STOPWATCH_HEARTRATE,*/UI_DISPLAY_STOPWATCH_HEARTRATE,
	/*UI_DISPLAY_STOPWATCH_CALORIES,*/UI_DISPLAY_STOPWATCH_CALORIES,
	/*UI_DISPLAY_STOPWATCH_RESULT,*/UI_DISPLAY_STOPWATCH_RESULT,
	// 7: Info menu
	/*UI_DISPLAY_WORKOUT_WALKING,*/                  UI_DISPLAY_WORKOUT_WALKING ,
	/*UI_DISPLAY_WORKOUT_RUNNING,*/                  UI_DISPLAY_WORKOUT_RUNNING,
	/*UI_DISPLAY_WORKOUT_ROW,*/                  UI_DISPLAY_WORKOUT_ROW,
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/                 UI_DISPLAY_WORKOUT_ELLIPTICAL,
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                 UI_DISPLAY_WORKOUT_STAIRS,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                 UI_DISPLAY_WORKOUT_CYCLING,
	/*UI_DISPLAY_WORKOUT_SWIMING,*/                 UI_DISPLAY_WORKOUT_SWIMING,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                 UI_DISPLAY_WORKOUT_OTHERS,
	/*UI_DISPLAY_WORKOUT_INDOOR,*/                    UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_OUTDOOR,*/                    UI_DISPLAY_WORKOUT_OUTDOOR,
	// 9: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_CAROUSEL_2,*/UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_CAROUSEL_3,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_CAROUSEL_4,*/UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_CAROUSEL_5,*/UI_DISPLAY_SMART_PHONE_FINDER,
	// 10: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/UI_DISPLAY_PREVIOUS,
};

const I8U ui_matrix_finger_up[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */ UI_DISPLAY_HOME,
	// 1: System
	/*UI_DISPLAY_DARK,*/UI_DISPLAY_DARK,
	/*UI_DISPLAY_CLING,*/UI_DISPLAY_CLING,
	/*UI_DISPLAY_OTA,*/UI_DISPLAY_OTA,
	/*UI_DISPLAY_PAIRING,*/UI_DISPLAY_PAIRING,
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_UV_IDX,*/UI_DISPLAY_TRACKER_UV_IDX,
	/*UI_DISPLAY_TRACKER_STEP,*/UI_DISPLAY_TRACKER_STEP,
	/*UI_DISPLAY_TRACKER_SLEEP,*/UI_DISPLAY_TRACKER_SLEEP,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_CALORIES,*/UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_MINUTES,*/UI_DISPLAY_TRACKER_MINUTES,
	/*UI_DISPLAY_TRACKER_CLOCK,*/UI_DISPLAY_TRACKER_CLOCK,
	/*UI_DISPLAY_TRACKER_NAME,*/UI_DISPLAY_TRACKER_NAME,
	// 3: a set of battery stats
	/*UI_DISPLAY_SMART_CALL,*/UI_DISPLAY_SMART_CALL,
	/*UI_DISPLAY_SMART_MESSAGE,*/UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_PHONE_FINDER,*/UI_DISPLAY_SMART_PHONE_FINDER,
	/*UI_DISPLAY_SMART_REMINDER,*/UI_DISPLAY_SMART_REMINDER,
	/*UI_DISPLAY_SMART_WEATHER,*/UI_DISPLAY_SMART_WEATHER,
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_VITAL_ACTIVE,*/UI_DISPLAY_VITAL_ACTIVE,
	/*UI_DISPLAY_VITAL_SUSPEND,*/UI_DISPLAY_VITAL_SUSPEND,
	/*UI_DISPLAY_VITAL_ENUM,*/UI_DISPLAY_VITAL_ENUM,
	/*UI_DISPLAY_VITAL_ERROR,*/UI_DISPLAY_VITAL_ERROR,
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/UI_DISPLAY_SETTING_VER,
	// 6: Confirmation messages
	/*UI_DISPLAY_STOPWATCH_START,*/ UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_STOPWATCH_STOP,*/UI_DISPLAY_STOPWATCH_STOP,
	/*UI_DISPLAY_STOPWATCH_HEARTRATE,*/UI_DISPLAY_STOPWATCH_HEARTRATE,
	/*UI_DISPLAY_STOPWATCH_CALORIES,*/UI_DISPLAY_STOPWATCH_CALORIES,
	/*UI_DISPLAY_STOPWATCH_RESULT,*/UI_DISPLAY_STOPWATCH_RESULT,
	// 7: Info menu
	/*UI_DISPLAY_WORKOUT_WALKING,*/UI_DISPLAY_WORKOUT_WALKING ,
	/*UI_DISPLAY_WORKOUT_RUNNING,*/UI_DISPLAY_WORKOUT_RUNNING,
	/*UI_DISPLAY_WORKOUT_ROW,*/UI_DISPLAY_WORKOUT_ROW,
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/UI_DISPLAY_WORKOUT_ELLIPTICAL,
	/*UI_DISPLAY_WORKOUT_STAIRS,*/UI_DISPLAY_WORKOUT_STAIRS,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/UI_DISPLAY_WORKOUT_CYCLING,
	/*UI_DISPLAY_WORKOUT_SWIMING,*/UI_DISPLAY_WORKOUT_SWIMING,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/UI_DISPLAY_WORKOUT_OTHERS,
	/*UI_DISPLAY_WORKOUT_INDOOR,*/UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_OUTDOOR,*/UI_DISPLAY_WORKOUT_OUTDOOR,
	// 9: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_CAROUSEL_2,*/UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_CAROUSEL_3,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_CAROUSEL_4,*/UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_CAROUSEL_5,*/UI_DISPLAY_SMART_PHONE_FINDER,
	// 10: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/UI_DISPLAY_PREVIOUS,
};

const I8U ui_matrix_finger_left[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */ UI_DISPLAY_HOME,
	// 1: System
	/*UI_DISPLAY_DARK,*/UI_DISPLAY_DARK,
	/*UI_DISPLAY_CLING,*/UI_DISPLAY_CLING,
	/*UI_DISPLAY_OTA,*/UI_DISPLAY_OTA,
	/*UI_DISPLAY_PAIRING,*/UI_DISPLAY_PAIRING,
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_UV_IDX,*/UI_DISPLAY_TRACKER_UV_IDX,
	/*UI_DISPLAY_TRACKER_STEP,*/UI_DISPLAY_TRACKER_STEP,
	/*UI_DISPLAY_TRACKER_SLEEP,*/UI_DISPLAY_TRACKER_SLEEP,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_CALORIES,*/UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_MINUTES,*/UI_DISPLAY_TRACKER_MINUTES,
	/*UI_DISPLAY_TRACKER_CLOCK,*/UI_DISPLAY_TRACKER_CLOCK,
	/*UI_DISPLAY_TRACKER_NAME,*/UI_DISPLAY_TRACKER_NAME,
	// 3: a set of battery stats
	/*UI_DISPLAY_SMART_CALL,*/UI_DISPLAY_SMART_CALL,
	/*UI_DISPLAY_SMART_MESSAGE,*/UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_PHONE_FINDER,*/UI_DISPLAY_SMART_PHONE_FINDER,
	/*UI_DISPLAY_SMART_REMINDER,*/UI_DISPLAY_SMART_REMINDER,
	/*UI_DISPLAY_SMART_WEATHER,*/UI_DISPLAY_SMART_WEATHER,
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_VITAL_ACTIVE,*/UI_DISPLAY_VITAL_ACTIVE,
	/*UI_DISPLAY_VITAL_SUSPEND,*/UI_DISPLAY_VITAL_SUSPEND,
	/*UI_DISPLAY_VITAL_ENUM,*/UI_DISPLAY_VITAL_ENUM,
	/*UI_DISPLAY_VITAL_ERROR,*/UI_DISPLAY_VITAL_ERROR,
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/UI_DISPLAY_HOME,
	// 6: Confirmation messages
	/*UI_DISPLAY_STOPWATCH_START,*/ UI_DISPLAY_STOPWATCH_STOP,
	/*UI_DISPLAY_STOPWATCH_STOP,*/UI_DISPLAY_STOPWATCH_RESULT,
	/*UI_DISPLAY_STOPWATCH_HEARTRATE,*/UI_DISPLAY_STOPWATCH_HEARTRATE,
	/*UI_DISPLAY_STOPWATCH_CALORIES,*/UI_DISPLAY_STOPWATCH_CALORIES,
	/*UI_DISPLAY_STOPWATCH_RESULT,*/UI_DISPLAY_HOME,
	// 7: Info menu
	/*UI_DISPLAY_WORKOUT_WALKING,*/UI_DISPLAY_HOME ,
	/*UI_DISPLAY_WORKOUT_RUNNING,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_WORKOUT_ROW,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_WORKOUT_STAIRS,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_WORKOUT_SWIMING,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_WORKOUT_INDOOR,*/UI_DISPLAY_HOME,
	/*UI_DISPLAY_WORKOUT_OUTDOOR,*/UI_DISPLAY_HOME,
	// 9: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_CAROUSEL_2,*/UI_DISPLAY_TRACKER_STEP,
	/*UI_DISPLAY_CAROUSEL_3,*/UI_DISPLAY_TRACKER_UV_IDX,
	/*UI_DISPLAY_CAROUSEL_4,*/UI_DISPLAY_WORKOUT_WALKING,
	/*UI_DISPLAY_CAROUSEL_5,*/UI_DISPLAY_SETTING_VER,
	// 10: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/UI_DISPLAY_PREVIOUS,
};

const I8U ui_matrix_finger_right[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */ UI_DISPLAY_HOME,
	// 1: System
	/*UI_DISPLAY_DARK,*/UI_DISPLAY_DARK,
	/*UI_DISPLAY_CLING,*/UI_DISPLAY_CLING,
	/*UI_DISPLAY_OTA,*/UI_DISPLAY_OTA,
	/*UI_DISPLAY_PAIRING,*/UI_DISPLAY_PAIRING,
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_UV_IDX,*/UI_DISPLAY_TRACKER_UV_IDX,
	/*UI_DISPLAY_TRACKER_STEP,*/UI_DISPLAY_TRACKER_STEP,
	/*UI_DISPLAY_TRACKER_SLEEP,*/UI_DISPLAY_TRACKER_SLEEP,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_CALORIES,*/UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_MINUTES,*/UI_DISPLAY_TRACKER_MINUTES,
	/*UI_DISPLAY_TRACKER_CLOCK,*/UI_DISPLAY_TRACKER_CLOCK,
	/*UI_DISPLAY_TRACKER_NAME,*/UI_DISPLAY_TRACKER_NAME,
	// 3: a set of battery stats
	/*UI_DISPLAY_SMART_CALL,*/UI_DISPLAY_SMART_CALL,
	/*UI_DISPLAY_SMART_MESSAGE,*/UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_PHONE_FINDER,*/UI_DISPLAY_SMART_PHONE_FINDER,
	/*UI_DISPLAY_SMART_REMINDER,*/UI_DISPLAY_SMART_REMINDER,
	/*UI_DISPLAY_SMART_WEATHER,*/UI_DISPLAY_SMART_WEATHER,
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_VITAL_ACTIVE,*/UI_DISPLAY_VITAL_ACTIVE,
	/*UI_DISPLAY_VITAL_SUSPEND,*/UI_DISPLAY_VITAL_SUSPEND,
	/*UI_DISPLAY_VITAL_ENUM,*/UI_DISPLAY_VITAL_ENUM,
	/*UI_DISPLAY_VITAL_ERROR,*/UI_DISPLAY_VITAL_ERROR,
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/UI_DISPLAY_SETTING_VER,
	// 6: Confirmation messages
	/*UI_DISPLAY_STOPWATCH_START,*/ UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_STOPWATCH_STOP,*/UI_DISPLAY_STOPWATCH_STOP,
	/*UI_DISPLAY_STOPWATCH_HEARTRATE,*/UI_DISPLAY_STOPWATCH_HEARTRATE,
	/*UI_DISPLAY_STOPWATCH_CALORIES,*/UI_DISPLAY_STOPWATCH_CALORIES,
	/*UI_DISPLAY_STOPWATCH_RESULT,*/UI_DISPLAY_STOPWATCH_RESULT,
	// 7: Info menu
	/*UI_DISPLAY_WORKOUT_WALKING,*/UI_DISPLAY_WORKOUT_WALKING ,
	/*UI_DISPLAY_WORKOUT_RUNNING,*/UI_DISPLAY_WORKOUT_RUNNING,
	/*UI_DISPLAY_WORKOUT_ROW,*/UI_DISPLAY_WORKOUT_ROW,
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/UI_DISPLAY_WORKOUT_ELLIPTICAL,
	/*UI_DISPLAY_WORKOUT_STAIRS,*/UI_DISPLAY_WORKOUT_STAIRS,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/UI_DISPLAY_WORKOUT_CYCLING,
	/*UI_DISPLAY_WORKOUT_SWIMING,*/UI_DISPLAY_WORKOUT_SWIMING,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/UI_DISPLAY_WORKOUT_OTHERS,
	/*UI_DISPLAY_WORKOUT_INDOOR,*/UI_DISPLAY_WORKOUT_INDOOR,
	/*UI_DISPLAY_WORKOUT_OUTDOOR,*/UI_DISPLAY_WORKOUT_OUTDOOR,
	// 9: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/UI_DISPLAY_SMART_WEATHER,
	/*UI_DISPLAY_CAROUSEL_2,*/UI_DISPLAY_TRACKER_SLEEP,
	/*UI_DISPLAY_CAROUSEL_3,*/UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_CAROUSEL_4,*/UI_DISPLAY_CAROUSEL_4,
	/*UI_DISPLAY_CAROUSEL_5,*/UI_DISPLAY_CAROUSEL_5,
	// 10: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/UI_DISPLAY_PREVIOUS,
};

const I8U ui_matrix_swipe_left[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */ UI_DISPLAY_SMART_REMINDER,
	// 1: System
	/*UI_DISPLAY_DARK,*/UI_DISPLAY_DARK,
	/*UI_DISPLAY_CLING,*/UI_DISPLAY_CLING,
	/*UI_DISPLAY_OTA,*/UI_DISPLAY_OTA,
	/*UI_DISPLAY_PAIRING,*/UI_DISPLAY_PAIRING,
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_UV_IDX,*/UI_DISPLAY_TRACKER_UV_IDX,
	/*UI_DISPLAY_TRACKER_STEP,*/UI_DISPLAY_TRACKER_STEP,
	/*UI_DISPLAY_TRACKER_SLEEP,*/UI_DISPLAY_TRACKER_SLEEP,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_CALORIES,*/UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_MINUTES,*/UI_DISPLAY_TRACKER_MINUTES,
	/*UI_DISPLAY_TRACKER_CLOCK,*/UI_DISPLAY_TRACKER_CLOCK,
	/*UI_DISPLAY_TRACKER_NAME,*/UI_DISPLAY_TRACKER_NAME,
	// 3: a set of battery stats
	/*UI_DISPLAY_SMART_CALL,*/UI_DISPLAY_SMART_CALL,
	/*UI_DISPLAY_SMART_MESSAGE,*/UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_PHONE_FINDER,*/UI_DISPLAY_SMART_PHONE_FINDER,
	/*UI_DISPLAY_SMART_REMINDER,*/UI_DISPLAY_SMART_REMINDER,
	/*UI_DISPLAY_SMART_WEATHER,*/UI_DISPLAY_SMART_WEATHER,
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/UI_DISPLAY_VITAL_HEART_RATE,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_VITAL_ACTIVE,*/UI_DISPLAY_VITAL_ACTIVE,
	/*UI_DISPLAY_VITAL_SUSPEND,*/UI_DISPLAY_VITAL_SUSPEND,
	/*UI_DISPLAY_VITAL_ENUM,*/UI_DISPLAY_VITAL_ENUM,
	/*UI_DISPLAY_VITAL_ERROR,*/UI_DISPLAY_VITAL_ERROR,
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/UI_DISPLAY_SETTING_VER,
	// 6: Confirmation messages
	/*UI_DISPLAY_STOPWATCH_START,*/ UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_STOPWATCH_STOP,*/UI_DISPLAY_STOPWATCH_HEARTRATE,
	/*UI_DISPLAY_STOPWATCH_HEARTRATE,*/UI_DISPLAY_STOPWATCH_CALORIES,
	/*UI_DISPLAY_STOPWATCH_CALORIES,*/UI_DISPLAY_STOPWATCH_STOP,
	/*UI_DISPLAY_STOPWATCH_RESULT,*/UI_DISPLAY_STOPWATCH_RESULT,
	// 7: Info menu
	/*UI_DISPLAY_WORKOUT_WALKING,*/UI_DISPLAY_WORKOUT_RUNNING ,
	/*UI_DISPLAY_WORKOUT_RUNNING,*/UI_DISPLAY_WORKOUT_ROW,
	/*UI_DISPLAY_WORKOUT_ROW,*/UI_DISPLAY_WORKOUT_ELLIPTICAL,
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/UI_DISPLAY_WORKOUT_STAIRS,
	/*UI_DISPLAY_WORKOUT_STAIRS,*/UI_DISPLAY_WORKOUT_CYCLING,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/UI_DISPLAY_WORKOUT_OTHERS,
	/*UI_DISPLAY_WORKOUT_SWIMING,*/UI_DISPLAY_WORKOUT_OTHERS,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/UI_DISPLAY_WORKOUT_WALKING,
	/*UI_DISPLAY_WORKOUT_INDOOR,*/UI_DISPLAY_WORKOUT_OUTDOOR,
	/*UI_DISPLAY_WORKOUT_OUTDOOR,*/UI_DISPLAY_WORKOUT_INDOOR,
	// 9: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/UI_DISPLAY_CAROUSEL_2,
	/*UI_DISPLAY_CAROUSEL_2,*/UI_DISPLAY_CAROUSEL_3,
	/*UI_DISPLAY_CAROUSEL_3,*/UI_DISPLAY_CAROUSEL_4,
	/*UI_DISPLAY_CAROUSEL_4,*/UI_DISPLAY_CAROUSEL_5,
	/*UI_DISPLAY_CAROUSEL_5,*/UI_DISPLAY_CAROUSEL_1,
	// 10: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/UI_DISPLAY_PREVIOUS,
};


const I8U ui_matrix_swipe_right[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */ UI_DISPLAY_SMART_REMINDER,
	// 1: System
	/*UI_DISPLAY_DARK,*/UI_DISPLAY_DARK,
	/*UI_DISPLAY_CLING,*/UI_DISPLAY_CLING,
	/*UI_DISPLAY_OTA,*/UI_DISPLAY_OTA,
	/*UI_DISPLAY_PAIRING,*/UI_DISPLAY_PAIRING,
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_UV_IDX,*/UI_DISPLAY_TRACKER_UV_IDX,
	/*UI_DISPLAY_TRACKER_STEP,*/UI_DISPLAY_TRACKER_STEP,
	/*UI_DISPLAY_TRACKER_SLEEP,*/UI_DISPLAY_TRACKER_SLEEP,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/UI_DISPLAY_TRACKER_DISTANCE,
	/*UI_DISPLAY_TRACKER_CALORIES,*/UI_DISPLAY_TRACKER_CALORIES,
	/*UI_DISPLAY_TRACKER_MINUTES,*/UI_DISPLAY_TRACKER_MINUTES,
	/*UI_DISPLAY_TRACKER_CLOCK,*/UI_DISPLAY_TRACKER_CLOCK,
	/*UI_DISPLAY_TRACKER_NAME,*/UI_DISPLAY_TRACKER_NAME,
	// 3: a set of battery stats
	/*UI_DISPLAY_SMART_CALL,*/UI_DISPLAY_SMART_CALL,
	/*UI_DISPLAY_SMART_MESSAGE,*/UI_DISPLAY_SMART_MESSAGE,
	/*UI_DISPLAY_SMART_PHONE_FINDER,*/UI_DISPLAY_SMART_PHONE_FINDER,
	/*UI_DISPLAY_SMART_REMINDER,*/UI_DISPLAY_SMART_REMINDER,
	/*UI_DISPLAY_SMART_WEATHER,*/UI_DISPLAY_SMART_WEATHER,
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/UI_DISPLAY_VITAL_SKIN_TEMP,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/UI_DISPLAY_TRACKER_SLEEP,
	/*UI_DISPLAY_VITAL_ACTIVE,*/UI_DISPLAY_VITAL_ACTIVE,
	/*UI_DISPLAY_VITAL_SUSPEND,*/UI_DISPLAY_VITAL_SUSPEND,
	/*UI_DISPLAY_VITAL_ENUM,*/UI_DISPLAY_VITAL_ENUM,
	/*UI_DISPLAY_VITAL_ERROR,*/UI_DISPLAY_VITAL_ERROR,
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/UI_DISPLAY_SETTING_VER,
	// 6: Confirmation messages
	/*UI_DISPLAY_STOPWATCH_START,*/ UI_DISPLAY_STOPWATCH_START,
	/*UI_DISPLAY_STOPWATCH_STOP,*/UI_DISPLAY_STOPWATCH_CALORIES,
	/*UI_DISPLAY_STOPWATCH_HEARTRATE,*/UI_DISPLAY_STOPWATCH_STOP,
	/*UI_DISPLAY_STOPWATCH_CALORIES,*/UI_DISPLAY_STOPWATCH_HEARTRATE,
	/*UI_DISPLAY_STOPWATCH_RESULT,*/UI_DISPLAY_STOPWATCH_RESULT,
	// 7: Info menu
	/*UI_DISPLAY_WORKOUT_WALKING,*/UI_DISPLAY_WORKOUT_OTHERS ,
	/*UI_DISPLAY_WORKOUT_RUNNING,*/UI_DISPLAY_WORKOUT_WALKING,
	/*UI_DISPLAY_WORKOUT_ROW,*/UI_DISPLAY_WORKOUT_RUNNING,
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/UI_DISPLAY_WORKOUT_ROW,
	/*UI_DISPLAY_WORKOUT_STAIRS,*/UI_DISPLAY_WORKOUT_ELLIPTICAL,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/UI_DISPLAY_WORKOUT_STAIRS,
	/*UI_DISPLAY_WORKOUT_SWIMING,*/UI_DISPLAY_WORKOUT_CYCLING,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/UI_DISPLAY_WORKOUT_CYCLING,
	/*UI_DISPLAY_WORKOUT_INDOOR,*/UI_DISPLAY_WORKOUT_OUTDOOR,
	/*UI_DISPLAY_WORKOUT_OUTDOOR,*/UI_DISPLAY_WORKOUT_INDOOR,
	// 9: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/UI_DISPLAY_CAROUSEL_5,
	/*UI_DISPLAY_CAROUSEL_2,*/UI_DISPLAY_CAROUSEL_1,
	/*UI_DISPLAY_CAROUSEL_3,*/UI_DISPLAY_CAROUSEL_2,
	/*UI_DISPLAY_CAROUSEL_4,*/UI_DISPLAY_CAROUSEL_3,
	/*UI_DISPLAY_CAROUSEL_5,*/UI_DISPLAY_CAROUSEL_4,
	// 10: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/UI_DISPLAY_PREVIOUS,
};

//
// UI FRAME GESTURE (UFG) constrains
//
#define UFG_NONE                         0x00
#define UFG_SWIPE_VERTICAL               0x01
#define UFG_SWIPE_HORIZONTAL             0x02
#define UFG_FINGER_IRIS                  0x04
#define UFG_DOUBLE_TAP                   0x08
#define UFG_SWIPE_VERTICAL_CONTENT       0x10
#define UFG_SWIPE_HORIZONTAL_CONTENT     0x20
#define UFG_BUTTON_SINGLE                0x40
#define UFG_BUTTON_HOLD                  0x80


#define V_H_I_A (UFG_SWIPE_VERTICAL | UFG_SWIPE_HORIZONTAL | UFG_FINGER_IRIS | UFG_DOUBLE_TAP)
#define I_A (UFG_FINGER_IRIS | UFG_DOUBLE_TAP)
#define VC_HC_I_A (UFG_SWIPE_HORIZONTAL_CONTENT | UFG_SWIPE_VERTICAL_CONTENT | UFG_FINGER_IRIS | UFG_DOUBLE_TAP)
#define N_T (UFG_NONE | UFG_DOUBLE_TAP)
#define N_S_HOLD (UFG_BUTTON_SINGLE | UFG_DOUBLE_TAP)

const I8U ui_gesture_constrain[UI_DISPLAY_MAXIMUM] = {
	// 0: Home
	/* UI_DISPLAY_HOME */                        V_H_I_A,
	// 1: System
	/*UI_DISPLAY_DARK,*/                         V_H_I_A,
	/*UI_DISPLAY_CLING,*/                        V_H_I_A,
	/*UI_DISPLAY_OTA,*/                           V_H_I_A,
	/*UI_DISPLAY_PAIRING,*/                      V_H_I_A,
	// 2: a set of the typical use cases
	/*UI_DISPLAY_TRACKER_UV_IDX,*/               N_S_HOLD,
	/*UI_DISPLAY_TRACKER_STEP,*/                 V_H_I_A,
	/*UI_DISPLAY_TRACKER_SLEEP,*/                V_H_I_A,
	/*UI_DISPLAY_TRACKER_DISTANCE,*/             V_H_I_A,
	/*UI_DISPLAY_TRACKER_CALORIES,*/             V_H_I_A,
	/*UI_DISPLAY_TRACKER_MINUTES,*/              V_H_I_A,
	/*UI_DISPLAY_TRACKER_CLOCK,*/                V_H_I_A,
	/*UI_DISPLAY_TRACKER_NAME,*/                 V_H_I_A,
	// 3: a set of battery stats
	/*UI_DISPLAY_SMART_CALL,*/                   V_H_I_A,
	/*UI_DISPLAY_SMART_MESSAGE,*/                N_S_HOLD,
	/*UI_DISPLAY_SMART_PHONE_FINDER,*/           N_S_HOLD,
	/*UI_DISPLAY_SMART_REMINDER,*/               V_H_I_A,
	/*UI_DISPLAY_SMART_WEATHER,*/                V_H_I_A,
	// 4: a set of VITAL
	/*UI_DISPLAY_VITAL_HEART_RATE,*/             N_S_HOLD,
	/*UI_DISPLAY_VITAL_SKIN_TEMP,*/              N_S_HOLD,
	/*UI_DISPLAY_VITAL_ACTIVE,*/                 V_H_I_A,
	/*UI_DISPLAY_VITAL_SUSPEND,*/                V_H_I_A,
	/*UI_DISPLAY_VITAL_ENUM,*/                   V_H_I_A,
	/*UI_DISPLAY_VITAL_ERROR,*/                  V_H_I_A,
	// 5: Special back panel mode
	/*UI_DISPLAY_SETTING_VER,*/                 V_H_I_A,
	// 6: Confirmation messages
	/*UI_DISPLAY_STOPWATCH_START,*/        V_H_I_A,
	/*UI_DISPLAY_STOPWATCH_STOP,*/           V_H_I_A,
	/*UI_DISPLAY_STOPWATCH_HEARTRATE,*/           V_H_I_A,
	/*UI_DISPLAY_STOPWATCH_CALORIES,*/           V_H_I_A,
	/*UI_DISPLAY_STOPWATCH_RESULT,*/           V_H_I_A,
	// 7: Info menu
	/*UI_DISPLAY_WORKOUT_WALKING,*/                  V_H_I_A ,
	/*UI_DISPLAY_WORKOUT_RUNNING,*/                  V_H_I_A,
	/*UI_DISPLAY_WORKOUT_ROW,*/                  V_H_I_A,
	/*UI_DISPLAY_WORKOUT_ELLIPTICAL,*/                 V_H_I_A,
	/*UI_DISPLAY_WORKOUT_STAIRS,*/                 V_H_I_A,
	/*UI_DISPLAY_WORKOUT_CYCLING,*/                 V_H_I_A,
	/*UI_DISPLAY_WORKOUT_SWIMING,*/                 V_H_I_A,
	/*UI_DISPLAY_WORKOUT_OTHERS,*/                 V_H_I_A,
	/*UI_DISPLAY_WORKOUT_INDOOR,*/                    V_H_I_A,
	/*UI_DISPLAY_WORKOUT_OUTDOOR,*/                    V_H_I_A,
	// 9: CAROUSEL
	/*UI_DISPLAY_CAROUSEL_1,*/                   V_H_I_A,
	/*UI_DISPLAY_CAROUSEL_2,*/                   V_H_I_A,
	/*UI_DISPLAY_CAROUSEL_3,*/                   V_H_I_A,
	/*UI_DISPLAY_CAROUSEL_4,*/                   V_H_I_A,
	/*UI_DISPLAY_CAROUSEL_5,*/                   V_H_I_A,
	// 10: PREVIOUS
	/*UI_DISPLAY_PREVIOUS*/                      V_H_I_A,
};

